###
POST http://localhost:3000/api/user HTTP/1.1
Content-Type: application/json

{
    "username": "Juan12",
    "name": "Juan Lopez",
    "email": "juan@gmail.com",
    "password": "juan123"
}


###
GET http://localhost:3000/api/user HTTP/1.1

###
GET http://localhost:3000/api/user/65e5588accce9fb011708bbc HTTP/1.1

###

PUT http://localhost:3000/api/user/65eb7650dba91091e2694a5a HTTP/1.1
Content-Type: application/json

{
    "username": "Juanito123",
    "name": "Juan Lopez",
    "email": "juan@gmail.com",
    "password": "juan123"
}


###
DELETE http://localhost:3000/api/user/65e8a54926498e11c8ecb98b HTTP/1.1


###
POST http://localhost:3000/api/horse HTTP/1.1
Content-Type: application/json

{
    "name": "ashbjsbxwkb",
    "age": "23",
    "breed": "bullterry",
    "diseases": "ninguna",
    "user": "65eb7650dba91091e2694a5a"

}

###
GET http://localhost:3000/api/horse HTTP/1.1

###
GET http://localhost:3000/api/horse/65ed156fbb2caabcaeb087cf HTTP/1.1

###
PUT http://localhost:3000/api/horse/65ed156fbb2caabcaeb087cf HTTP/1.1
Content-Type: application/json

{
    "name": "Samaritano",
    "age": "23",
    "breed": "no se que es breed",
    "diseases": "ninguna",
    "user": "65eb7650dba91091e2694a5a"

}

###
DELETE http://localhost:3000/api/horse/660f764298f5a33e526e83fa HTTP/1.1

###
POST http://localhost:3000/api/vets HTTP/1.1
Content-Type: application/json

{
    "firstName": "Rodrigo",
    "lastName": "Lopez",
    "age": "25",
    "email": "rodrigo@gmail.com",
    "phone": "1542369585"
}

###
GET http://localhost:3000/api/vets HTTP/1.1

###
GET http://localhost:3000/api/vets/66109d7825235b008b473097 HTTP/1.1

###
PUT http://localhost:3000/api/vets/660f66597e38180a748f7e9b HTTP/1.1
Content-Type: application/json

{
    "firstName": "Sergio Chiquito",
    "lastName": "Amador",
    "age": "19",
    "email": "sergio@gmail.com",
    "phone": "6188236422"

}

###
DELETE http://localhost:3000/api/vets/6610d632dfe1cd9e4f43e8b3 HTTP/1.1

###
POST http://localhost:3000/api/checks HTTP/1.1
Content-Type: application/json

{
    "name": "Samaritano2",
    "medicines": "suerito",
    "specifications": "anduvo triston",
    "food": "una paca",
    "horseshoes": "todavia awantan",
    "job": "8 horas"
}

###
GET http://localhost:3000/api/checks HTTP/1.1

###
GET http://localhost:3000/api/checks/6614cfadabbf3b53b8877eb2

###
PUT http://localhost:3000/api/checks/6614cfadabbf3b53b8877eb2 HTTP/1.1
Content-Type: application/json

{
    "name": "firulais",
    "medicines": "sueritos",
    "specifications": "anduvo tristones",
    "food": "una pacaasd",
    "horseshoes": "todavia awantan",
    "job": "8 horas"
}

###
DELETE http://localhost:3000/api/checks/6614cfadabbf3b53b8877eb2 HTTP/1.1
